In [3]:
from instancepipeline import get_data_loaders

Train samples: 979487
Validation samples: 96993
Test samples: 82769
Train batches: 7653
Val batches: 758
Test batches: 647

In [ ]:
train_loader,val_loader,test_loader = get_data_loaders()

In [6]:
import torch
import torch.nn

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [8]:
TARGET_MEAN = 2.28802128052746

In [9]:
import pandas as pd

In [11]:
all_targets = []

for waveforms, magnitudes in train_loader:

    magnitudes = magnitudes.to(device)

    magnitudes = magnitudes + TARGET_MEAN

    all_targets.append(
        magnitudes.cpu()
    )


all_targets = torch.cat(
    all_targets
).numpy()


targets = pd.DataFrame({
    "magnitude": all_targets
})


targets.head(5)

   magnitude
0        3.3
1        2.0
2        2.1
3        2.5
4        4.0

In [26]:
bin = 0

bins = []
counts = []

while bin < 6.6:

    bins.append(bin)

    count = (
        (targets["magnitude"] >= bin)
        & (targets["magnitude"] < bin + 0.1)
    ).sum()

    counts.append(count)

    bin = round(bin + 0.1, 1)

prior = pd.DataFrame({
    "bins": bins,
    "counts": counts
})

prior["probability"] = (
    prior["counts"] / prior["counts"].sum()
)

In [27]:
prior

    bins  counts  probability
0    0.0      95     0.000097
1    0.1       0     0.000000
2    0.2     695     0.000710
3    0.3    1363     0.001392
4    0.4       0     0.000000
..   ...     ...          ...
61   6.1      50     0.000051
62   6.2       0     0.000000
63   6.3       0     0.000000
64   6.4       0     0.000000
65   6.5      75     0.000077

[66 rows x 3 columns]

In [20]:
prior["probability"] = (
    prior["counts"] / prior["counts"].sum()
)

In [21]:
prior

    bins  counts  probability
0    0.0      95     0.000097
1    0.1       0     0.000000
2    0.2     695     0.000710
3    0.3    1363     0.001392
4    0.4       0     0.000000
5    0.5    2076     0.002120
6    0.6    2804     0.002863
7    0.7   12394     0.012656
8    0.8       0     0.000000
9    0.9   10734     0.010961
10   1.0   13779     0.014070
11   1.1   15506     0.015833
12   1.2   19620     0.020034
13   1.3   19675     0.020090
14   1.4   19406     0.019816
15   1.5   18871     0.019269
16   1.6   17984     0.018364
17   1.7   15328     0.015652
18   1.8   13631     0.013919
19   1.9   12135     0.012391
20   2.0  109616     0.111930
21   2.1   96397     0.098432
22   2.2   88570     0.090440
23   2.3   72826     0.074364
24   2.4   64785     0.066153
25   2.5   59954     0.061220
26   2.6   48978     0.050012
27   2.7   41562     0.042440
28   2.8   34526     0.035255
29   2.9   28383     0.028982
30   3.0   25092     0.025622
31   3.1   20790     0.021229
32   3.2   17823     0.018199
33   3.3   14508     0.014814
34   3.4   11345     0.011585
35   3.5    9895     0.010104
36   3.6    5703     0.005823
37   3.7    6226     0.006357
38   3.8    3927     0.004010
39   3.9    4082     0.004168
40   4.0    4189     0.004277
41   4.1    2421     0.002472
42   4.2    2539     0.002593
43   4.3    2156     0.002202
44   4.4    1626     0.001660
45   4.5    1439     0.001469
46   4.6     616     0.000629
47   4.7     598     0.000611
48   4.8     687     0.000702
49   4.9     466     0.000476
50   5.0     453     0.000463
51   5.1     145     0.000148
52   5.2      97     0.000099
53   5.3      48     0.000049
54   5.4     322     0.000329
55   5.5      43     0.000044
56   5.6      45     0.000046
57   5.7       0     0.000000
58   5.8     277     0.000283
59   5.9      72     0.000074

In [23]:
print(targets["magnitude"].min())
print(targets["magnitude"].max())
print(prior["counts"].sum())
print(len(targets))

0.0
6.5
979323
979487

In [28]:
prior.to_csv("initialprior.csv",index=False)

In [30]:
from instancepipelineprior import get_data_loaders
train_loader, val_loader, test_loader = get_data_loaders()

_, y = next(iter(train_loader))

print("min:", y.min().item())
print("max:", y.max().item())
print("mean:", y.mean().item())

min: 0.6000000238418579
max: 3.9000000953674316
mean: 2.2835936546325684

In [31]:
MIN_MAGNITUDE = 0.0
MAX_MAGNITUDE = 6.6
BIN_WIDTH = 0.1



BIN_CENTERS = torch.arange(
    MIN_MAGNITUDE + BIN_WIDTH / 2,
    MAX_MAGNITUDE,
    BIN_WIDTH,
    dtype=torch.float32
)
NUM_BINS = len(BIN_CENTERS)

In [33]:
from discretizedtrain import EarthquakeCNN, logits_to_magnitude

In [36]:
model = EarthquakeCNN()
model = model.to(device)

In [37]:
print(NUM_BINS)
print(BIN_CENTERS.shape)

data, target = next(iter(train_loader))
data = data.to(device)

with torch.no_grad():
    logits = model(data)
    predictions = logits_to_magnitude(logits, BIN_CENTERS.to(device))

print(logits.shape)
print(predictions.shape)
print(target.shape)
print(predictions[:5])
print(target[:5])

66
torch.Size([66])

torch.Size([128, 66])
torch.Size([128])
torch.Size([128])
tensor([3.2844, 3.2890, 3.2933, 3.2895, 3.2885], device='cuda:0')
tensor([2.0000, 1.7000, 2.3000, 1.9000, 2.5000])