In [1]:
import optuna
import pandas as pd

study = optuna.load_study(
    study_name="earthquake_architecture_search",
    storage="sqlite:///../architechturesearch/data/architecture_search.db"
)

df = study.trials_dataframe()

print(df.head())

   number     value             datetime_start          datetime_complete  \
0       0  0.569046 2026-08-24 16:24:35.526694 2026-08-24 16:27:34.938984
1       1  0.537304 2026-08-24 16:27:34.956482 2026-08-24 16:30:26.892518
2       2  0.655814 2026-08-24 16:30:26.906516 2026-08-24 16:34:01.079800
3       3  0.564750 2026-08-24 16:34:01.091502 2026-08-24 16:37:01.287086
4       4  0.617403 2026-08-24 16:37:01.298667 2026-08-24 16:39:39.746640

                duration  params_fc_size  params_initial_filters  \
0 0 days 00:02:59.412290             128                      16
1 0 days 00:02:51.936036             128                      32
2 0 days 00:03:34.173284             256                      32
3 0 days 00:03:00.195584             256                      64
4 0 days 00:02:38.447973              64                      64

   params_kernel_size  params_n_layers  params_use_batchnorm  \
0                   3                6                 False
1                   5                5                 False
2                   3                6                  True
3                   5                5                 False
4                   3                3                 False

   user_attrs_best_epoch  user_attrs_best_val_accuracy_0.2  \
0                     17                         33.864299
1                     16                         34.225150
2                     17                         32.727104
3                     16                         33.732331
4                     17                         29.225820

   user_attrs_best_val_mae  user_attrs_best_val_mse  user_attrs_best_val_rmse  \
0                 0.430023                 0.323814                  0.569046
1                 0.408528                 0.288695                  0.537304
2                 0.482295                 0.430092                  0.655814
3                 0.427052                 0.318942                  0.564750
4                 0.479370                 0.381187                  0.617403

   user_attrs_trainable_params     state
0                       361089  COMPLETE
1                       576961  COMPLETE
2                       591553  COMPLETE
3                       928129  COMPLETE
4                       140417  COMPLETE

In [2]:
complete_df = df[df["state"] == "COMPLETE"]

In [6]:
complete_df.sort_values("value")

,number,value,datetime_start,datetime_complete,duration,params_fc_size,params_initial_filters,params_kernel_size,params_n_layers,params_use_batchnorm,user_attrs_best_epoch,user_attrs_best_val_accuracy_0.2,user_attrs_best_val_mae,user_attrs_best_val_mse,user_attrs_best_val_rmse,user_attrs_trainable_params,state
1,1,0.537304,2026-08-24 16:27:34.956482,2026-08-24 16:30:26.892518,0 days 00:02:51.936036,128,32,5,5,False,16,34.225150,0.408528,0.288695,0.537304,576961,COMPLETE
28,28,0.546818,2026-08-24 17:04:49.603853,2026-08-24 17:07:52.921657,0 days 00:03:03.317804,128,16,7,6,False,17,34.892209,0.411151,0.299010,0.546818,797505,COMPLETE
22,22,0.547066,2026-08-24 16:54:57.513275,2026-08-24 16:57:58.228549,0 days 00:03:00.715274,128,16,3,6,False,17,33.214768,0.417786,0.299281,0.547066,361089,COMPLETE
3,3,0.564750,2026-08-24 16:34:01.091502,2026-08-24 16:37:01.287086,0 days 00:03:00.195584,256,64,5,5,False,16,33.732331,0.427052,0.318942,0.564750,928129,COMPLETE
0,0,0.569046,2026-08-24 16:24:35.526694,2026-08-24 16:27:34.938984,0 days 00:02:59.412290,128,16,3,6,False,17,33.864299,0.430023,0.323814,0.569046,361089,COMPLETE
4,4,0.617403,2026-08-24 16:37:01.298667,2026-08-24 16:39:39.746640,0 days 00:02:38.447973,64,64,3,3,False,17,29.225820,0.479370,0.381187,0.617403,140417,COMPLETE
2,2,0.655814,2026-08-24 16:30:26.906516,2026-08-24 16:34:01.079800,0 days 00:03:34.173284,256,32,3,6,True,17,32.727104,0.482295,0.430092,0.655814,591553,COMPLETE

In [4]:
pruned_df = df[df["state"] == "PRUNED"]

In [8]:
pruned_df.sort_values("value")

,number,value,datetime_start,datetime_complete,duration,params_fc_size,params_initial_filters,params_kernel_size,params_n_layers,params_use_batchnorm,user_attrs_best_epoch,user_attrs_best_val_accuracy_0.2,user_attrs_best_val_mae,user_attrs_best_val_mse,user_attrs_best_val_rmse,user_attrs_trainable_params,state
23,23,0.589067,2026-08-24 16:57:58.240208,2026-08-24 17:00:16.417503,0 days 00:02:18.177295,128,16,3,6,False,13,32.869382,0.447033,0.347000,0.589067,361089,PRUNED
24,24,0.617314,2026-08-24 17:00:16.427577,2026-08-24 17:01:37.614487,0 days 00:01:21.186910,128,16,5,5,False,8,32.483787,0.464235,0.381076,0.617314,251361,PRUNED
27,27,0.617607,2026-08-24 17:03:27.669843,2026-08-24 17:04:49.594076,0 days 00:01:21.924233,64,32,5,5,False,8,34.431351,0.465769,0.381438,0.617607,560449,PRUNED
6,6,0.629211,2026-08-24 16:40:20.219401,2026-08-24 16:41:20.917448,0 days 00:01:00.698047,64,32,5,5,False,3,32.604415,0.474806,0.394777,0.628313,560449,PRUNED
16,16,0.630675,2026-08-24 16:48:26.102422,2026-08-24 16:50:58.944082,0 days 00:02:32.841660,256,32,5,5,False,11,32.289959,0.439034,0.332343,0.576492,609985,PRUNED
25,25,0.630901,2026-08-24 17:01:37.624353,2026-08-24 17:02:41.922176,0 days 00:01:04.297823,256,32,3,6,False,6,32.838452,0.477764,0.398037,0.630901,589569,PRUNED
29,29,0.632126,2026-08-24 17:07:52.933121,2026-08-24 17:08:57.766100,0 days 00:01:04.832979,128,16,7,6,False,5,33.798315,0.474456,0.397129,0.630182,797505,PRUNED
14,14,0.632758,2026-08-24 16:46:22.663873,2026-08-24 16:47:40.187104,0 days 00:01:17.523231,256,16,5,4,False,6,33.863268,0.466869,0.384950,0.620443,87521,PRUNED
7,7,0.639000,2026-08-24 16:41:20.927148,2026-08-24 16:42:23.051129,0 days 00:01:02.123981,128,64,3,5,False,4,34.205561,0.475458,0.399149,0.631782,550657,PRUNED
15,15,0.663098,2026-08-24 16:47:40.197030,2026-08-24 16:48:26.092698,0 days 00:00:45.895668,128,64,5,6,False,4,33.199303,0.498572,0.439700,0.663098,1223041,PRUNED
19,19,0.663169,2026-08-24 16:52:33.070533,2026-08-24 16:53:34.072583,0 days 00:01:01.002050,256,16,5,5,False,5,32.085821,0.472022,0.390195,0.624656,284385,PRUNED
21,21,0.670938,2026-08-24 16:54:14.974520,2026-08-24 16:54:57.503579,0 days 00:00:42.529059,128,16,3,6,False,4,30.254761,0.504249,0.450158,0.670938,361089,PRUNED
17,17,0.673985,2026-08-24 16:50:58.954159,2026-08-24 16:51:38.081823,0 days 00:00:39.127664,32,32,7,4,False,4,35.094285,0.502734,0.454255,0.673985,310465,PRUNED
13,13,0.676161,2026-08-24 16:45:42.074731,2026-08-24 16:46:22.654109,0 days 00:00:40.579378,32,32,5,5,False,3,33.390038,0.491785,0.425742,0.652489,552193,PRUNED
9,9,0.680532,2026-08-24 16:42:58.024118,2026-08-24 16:43:38.070444,0 days 00:00:40.046326,64,16,7,3,True,4,37.390327,0.501788,0.463124,0.680532,22817,PRUNED
8,8,0.686535,2026-08-24 16:42:23.060759,2026-08-24 16:42:58.014397,0 days 00:00:34.953638,128,64,3,2,False,3,37.221243,0.510364,0.469996,0.685562,41985,PRUNED
20,20,0.688495,2026-08-24 16:53:34.082258,2026-08-24 16:54:14.964716,0 days 00:00:40.882458,128,64,7,4,False,4,37.673853,0.510742,0.474025,0.688495,780545,PRUNED
5,5,0.688987,2026-08-24 16:39:39.758302,2026-08-24 16:40:20.209848,0 days 00:00:40.451546,128,64,5,3,True,4,32.394090,0.505111,0.474703,0.688987,240129,PRUNED
11,11,0.700565,2026-08-24 16:44:20.398803,2026-08-24 16:45:01.140183,0 days 00:00:40.741380,256,32,5,5,False,3,31.678575,0.504521,0.463183,0.680576,609985,PRUNED
12,12,0.714142,2026-08-24 16:45:01.149837,2026-08-24 16:45:42.064819,0 days 00:00:40.914982,256,64,5,4,False,3,37.273824,0.508601,0.490296,0.700212,600193,PRUNED
26,26,1.384061,2026-08-24 17:02:41.932012,2026-08-24 17:03:27.660009,0 days 00:00:45.727997,32,16,5,5,True,2,10.111039,0.735803,0.779519,0.882904,227585,PRUNED
18,18,1.453140,2026-08-24 16:51:38.091395,2026-08-24 16:52:33.060693,0 days 00:00:54.969298,128,64,5,6,True,2,20.339612,0.554880,0.562415,0.749943,1225473,PRUNED
10,10,1.572354,2026-08-24 16:43:38.080184,2026-08-24 16:44:20.388925,0 days 00:00:42.308741,32,32,7,4,True,3,26.816368,0.528843,0.572573,0.756685,311425,PRUNED

Based on these results, the clear ideas are that 
1. BatchNorm = False
2. Layers best options between 5 and 6
3. Initial filters best at 16 or 32
4. Kernel size 3 or 5 best 
5. fc size 128 or 256 initiall ybest

Bigger models does not suggest better results, run to run variance is high

In [20]:
study2= optuna.load_study(
    study_name="earthquake_architecture_search",
    storage="sqlite:///../architechturesearch/data/architecture_search2.db"
)

df2 = study2.trials_dataframe()

print(df2.head())

   number     value             datetime_start          datetime_complete  \
0       0       NaN 2026-08-25 10:57:35.806248 2026-08-25 10:57:59.472576
1       1  0.528469 2026-08-25 10:58:23.759743 2026-08-25 11:02:16.302874
2       2  0.546275 2026-08-25 11:02:16.320725 2026-08-25 11:05:58.161332
3       3  0.536062 2026-08-25 11:05:58.173284 2026-08-25 11:09:41.887651
4       4  0.551470 2026-08-25 11:09:41.899462 2026-08-25 11:13:25.949723

                duration  params_fc_size  params_initial_filters  \
0 0 days 00:00:23.666328             512                      32
1 0 days 00:03:52.543131             512                      32
2 0 days 00:03:41.840607             256                      16
3 0 days 00:03:43.714367             512                      16
4 0 days 00:03:44.050261             128                      16

   params_kernel_size  params_n_layers  user_attrs_best_epoch  \
0                   3                5                      1
1                   5                6                     19
2                   5                6                     15
3                   5                6                     19
4                   3                6                     20

   user_attrs_best_val_accuracy_0.2  user_attrs_best_val_mae  \
0                         31.029043                 0.513529
1                         35.455136                 0.398426
2                         33.842648                 0.415498
3                         34.204530                 0.406102
4                         32.849793                 0.422048

   user_attrs_best_val_mse  user_attrs_best_val_rmse  \
0                 0.477705                  0.691162
1                 0.279279                  0.528469
2                 0.298417                  0.546275
3                 0.287363                  0.536062
4                 0.304119                  0.551470

   user_attrs_trainable_params     state
0                       458753      FAIL
1                      2446273  COMPLETE
2                      1005793  COMPLETE
3                      1137377  COMPLETE
4                       590721  COMPLETE

In [21]:
completed2 = df2[df2["state"] == "COMPLETE"]

In [22]:
completed2.sort_values("value")

,number,value,datetime_start,datetime_complete,duration,params_fc_size,params_initial_filters,params_kernel_size,params_n_layers,user_attrs_best_epoch,user_attrs_best_val_accuracy_0.2,user_attrs_best_val_mae,user_attrs_best_val_mse,user_attrs_best_val_rmse,user_attrs_trainable_params,state
1,1,0.528469,2026-08-25 10:58:23.759743,2026-08-25 11:02:16.302874,0 days 00:03:52.543131,512,32,5,6,19,35.455136,0.398426,0.279279,0.528469,2446273,COMPLETE
3,3,0.536062,2026-08-25 11:05:58.173284,2026-08-25 11:09:41.887651,0 days 00:03:43.714367,512,16,5,6,19,34.204530,0.406102,0.287363,0.536062,1137377,COMPLETE
2,2,0.546275,2026-08-25 11:02:16.320725,2026-08-25 11:05:58.161332,0 days 00:03:41.840607,256,16,5,6,15,33.842648,0.415498,0.298417,0.546275,1005793,COMPLETE
4,4,0.551470,2026-08-25 11:09:41.899462,2026-08-25 11:13:25.949723,0 days 00:03:44.050261,128,16,3,6,20,32.849793,0.422048,0.304119,0.551470,590721,COMPLETE
5,5,0.586977,2026-08-25 11:13:25.961657,2026-08-25 11:17:01.171465,0 days 00:03:35.209808,128,16,3,5,20,31.424948,0.449986,0.344542,0.586977,164225,COMPLETE

In [24]:
meanof256 = completed2[completed2["params_fc_size"] == 256]["value"].mean()

meanof512 = completed2[completed2["params_fc_size"] == 512]["value"].mean()

print(meanof256)
print(meanof512)

0.5462751641140442
0.5322654717369859

In [23]:
meanof256 = df2[df2["params_fc_size"] == 256]["value"].mean()

meanof512 = df2[df2["params_fc_size"] == 512]["value"].mean()

print(meanof256)
print(meanof512)

0.6059669573080396
0.6159284180214685

In [ ]:
study3= optuna.load_study(
    study_name="earthquake_architecture_searchfc2",
    storage="sqlite:///../architechturesearch/data/architecture_search3.db"
)

df3 = study3.trials_dataframe()

print(df3.head())

KeyError: 'Record does not exist.'

In [26]:
df3.head(5)

,number,value,datetime_start,datetime_complete,duration,params_fc_size,params_initial_filters,params_kernel_size,params_n_layers,user_attrs_best_epoch,user_attrs_best_val_accuracy_0.2,user_attrs_best_val_mae,user_attrs_best_val_mse,user_attrs_best_val_rmse,user_attrs_trainable_params,state
0,0,NaN,2026-08-25 10:57:35.806248,2026-08-25 10:57:59.472576,0 days 00:00:23.666328,512,32,3,5,1,31.029043,0.513529,0.477705,0.691162,458753,FAIL
1,1,0.528469,2026-08-25 10:58:23.759743,2026-08-25 11:02:16.302874,0 days 00:03:52.543131,512,32,5,6,19,35.455136,0.398426,0.279279,0.528469,2446273,COMPLETE
2,2,0.546275,2026-08-25 11:02:16.320725,2026-08-25 11:05:58.161332,0 days 00:03:41.840607,256,16,5,6,15,33.842648,0.415498,0.298417,0.546275,1005793,COMPLETE
3,3,0.536062,2026-08-25 11:05:58.173284,2026-08-25 11:09:41.887651,0 days 00:03:43.714367,512,16,5,6,19,34.204530,0.406102,0.287363,0.536062,1137377,COMPLETE
4,4,0.551470,2026-08-25 11:09:41.899462,2026-08-25 11:13:25.949723,0 days 00:03:44.050261,128,16,3,6,20,32.849793,0.422048,0.304119,0.551470,590721,COMPLETE

In [27]:
completed_df3 = df3[df3["state"] == "COMPLETE"]
completed_df3

,number,value,datetime_start,datetime_complete,duration,params_fc_size,params_initial_filters,params_kernel_size,params_n_layers,user_attrs_best_epoch,user_attrs_best_val_accuracy_0.2,user_attrs_best_val_mae,user_attrs_best_val_mse,user_attrs_best_val_rmse,user_attrs_trainable_params,state
1,1,0.528469,2026-08-25 10:58:23.759743,2026-08-25 11:02:16.302874,0 days 00:03:52.543131,512,32,5,6,19,35.455136,0.398426,0.279279,0.528469,2446273,COMPLETE
2,2,0.546275,2026-08-25 11:02:16.320725,2026-08-25 11:05:58.161332,0 days 00:03:41.840607,256,16,5,6,15,33.842648,0.415498,0.298417,0.546275,1005793,COMPLETE
3,3,0.536062,2026-08-25 11:05:58.173284,2026-08-25 11:09:41.887651,0 days 00:03:43.714367,512,16,5,6,19,34.204530,0.406102,0.287363,0.536062,1137377,COMPLETE
4,4,0.551470,2026-08-25 11:09:41.899462,2026-08-25 11:13:25.949723,0 days 00:03:44.050261,128,16,3,6,20,32.849793,0.422048,0.304119,0.551470,590721,COMPLETE
5,5,0.586977,2026-08-25 11:13:25.961657,2026-08-25 11:17:01.171465,0 days 00:03:35.209808,128,16,3,5,20,31.424948,0.449986,0.344542,0.586977,164225,COMPLETE